name: hack_improved
description: "Hack game improved"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.32.0
  flame_markdown: ^0.2.4+9
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  flame_bloc: ^1.12.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.8.0
  freezed: ^3.2.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash_background.png
    - assets/images/connection.png
    - assets/images/wifi.png
    - assets/images/battery.png
    - assets/images/blue_server.png
    - assets/images/green_server.png
    - assets/images/red_server.png
    - assets/images/alert_icon.png
    - assets/images/check.png
    - assets/images/folder.png
    - assets/images/node.png
    - assets/images/human.png
    - assets/images/arrows.png
    - assets/images/phase0_icons/chat.png
    - assets/images/phase0_icons/contacts.png
    - assets/images/phase0_icons/epd.png
    - assets/images/phase0_icons/docs.png
    - assets/images/phase0_icons/power.png
    - assets/images/phase0_icons/network.png
    - assets/images/phase0_icons/pager.png
    - assets/images/phase0_icons/mail.png
    - assets/images/phase0_icons/chat_blackout.png
    - assets/images/phase0_icons/contacts_blackout.png
    - assets/images/phase0_icons/epd_blackout.png
    - assets/images/phase0_icons/docs_blackout.png
    - assets/images/phase0_icons/power_blackout.png
    - assets/images/phase0_icons/network_blackout.png
    - assets/images/phase0_icons/pager_blackout.png
    - assets/images/phase0_icons/mail_blackout.png
    - assets/images/Infected.png
    - assets/images/Connection.png
    - assets/images/Safe.png
    - assets/images/phase0_icons/png_location.png
    - assets/images/phase0_icons/png_calendar.png
    - assets/images/employee1.png
    - assets/images/employee2.png
    - assets/images/employee3.png
    # - assets/images/Observation.png
    # - assets/images/Background before hack.png
    # - assets/images/Background after hack.png
    - assets/images/escape_the hack_logo.png
    - assets/images/splash_background.png
    - assets/images/phase0_icons/weather.png
    - assets/images/phase0_icons/calendar.png
    - assets/images/background_basescreen.png
    - assets/images/phase0_icons/wifi_white.png
    - assets/images/phase0_icons/battery_white.png
    - assets/images/phase0_icons/connection_white.png
    - assets/images/phase0_icons/wifi_black.png
    - assets/images/phase0_icons/battery_black.png
    - assets/images/phase0_icons/connection_black.png
    - assets/images/phase0_icons/hacker_background.png
    - assets/images/phase0_icons/afterhack_weather.png
    - assets/images/phase0_icons/afterhack_calendar.png
    # - assets/images/mail.png
    # - assets/images/Infected.png
    # - assets/images/Connection.png
    # - assets/images/Safe.png
    # - assets/images/Observation.png
    # - assets/images/greenserver.png
    # - assets/images/redserver.png
    # - assets/images/blueserver.png
    # - assets/images/serverlog2.png
    # - assets/images/serverlog3.png
    # - assets/images/serverlog4.png
    # - assets/images/serverlog5.png
