name: hack_improved
description: "Hack game improved"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.32.0
  flame_markdown: ^0.2.4+9
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  flame_bloc: ^1.12.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.8.0
  freezed: ^3.2.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/splash_background.png
    - assets/images/connection.png
    - assets/images/wifi.png
    - assets/images/battery.png
    - assets/images/blue_server.png
    - assets/images/green_server.png
    - assets/images/red_server.png
    - assets/images/alert_icon.png
    - assets/images/check.png
    - assets/images/folder.png
    - assets/images/node.png
    - assets/images/human.png
    - assets/images/arrows.png
    # - assets/images/mail.png
    # - assets/images/Infected.png
    # - assets/images/Connection.png
    # - assets/images/Safe.png
    # - assets/images/Observation.png
    # - assets/images/greenserver.png
    # - assets/images/redserver.png
    # - assets/images/blueserver.png
    # - assets/images/serverlog2.png
    # - assets/images/serverlog3.png
    # - assets/images/serverlog4.png
    # - assets/images/serverlog5.png
